### ISSUE TITLE
Failed Interaction when i select an option of the menu.

### ISSUE THREAD

**Issue by HarpyLMAO** [lilmayu/MayusJDAUtilities#5] opened 2021-12-25 21:41 UTC
When I select an option of the selection menu says this:

![image](https://user-images.githubusercontent.com/44677087/147394011-9a745cdc-1a8d-49a3-af46-ab6cf6334123.png)

The code is the same of the documentation, i copied to test. 

`InteractiveMessage iMessage = InteractiveMessage.createSelectionMenu(
                new MessageBuilder().setEmbeds(MessageInfo.informationEmbed("Please, select your birthday month.").build())
        );

        for (int monthIndex = 0; monthIndex < 12; monthIndex++) {
            String month = new DateFormatSymbols().getMonths()[monthIndex]; // Gets name of the month by it's number
            iMessage.addInteraction(Interaction.asSelectOption(DiscordUtils.generateSelectOption((monthIndex + 1) + ": " + month)), () -> {

                InteractiveMessage selectedMessage = InteractiveMessage.create(
                        new MessageBuilder()
                                .setEmbeds(MessageInfo.successEmbed("Successfully selected " + month + " as your birthday month!").build())
                );
                selectedMessage.addInteraction(Interaction.asButton(DiscordUtils.generateCloseButton(ButtonStyle.DANGER)), selectedMessage::delete);
                selectedMessage.editMessage(iMessage.getMessage());
            });
        }
        iMessage.sendMessage(textChannel);`

**Comment by lilmayu** [comment] 2021-12-25 21:45
Maybe I have the solution right away: Have you registered event listener `MayuCoreListener`? You can get a bit more info [here](https://docs.mayuna.dev/mayus-jda-utilities/interactive-message) (I am in process of rewriting entire docs there)

**Comment by HarpyLMAO** [comment] 2021-12-25 22:46
> Maybe I have the solution right away: Have you registered event listener `MayuCoreListener`? You can get a bit more info [here](https://docs.mayuna.dev/mayus-jda-utilities/interactive-message) (I am in process of rewriting entire docs there)

Yes I did it. Because its not only with your API, If I make the same without the api the SelectionMenuEvent the event doesn't work or if I make the same with EventWaiter

**Comment by lilmayu** [comment] 2021-12-25 23:03
Which JDA version are you using?

**Comment by HarpyLMAO** [comment] 2021-12-25 23:04
> Which JDA version are you using?

5.0 beta, but i tested 4.3.0, 4.4.0 and much more

**Comment by lilmayu** [comment] 2021-12-25 23:08
Okay; Can you show me your main class?

**Comment by HarpyLMAO** [comment] 2021-12-25 23:09
`@Getter
public class Bot {

  @Getter
  private static Bot instance;

  private JDA jda;

  private String eustaquioId = "..";

  private MongoConnector mongoConnector;

  private MusicManager guildAudioManager;
  private EustaquioManager eustaquioManager;
  private UserManager userManager;

  private EventWaiter eventWaiter;

  private Bot() throws Exception {
    instance = this;

    this.mongoConnector = new MongoConnector(this);
    this.mongoConnector.load();

    this.eustaquioManager = new EustaquioManager(mongoConnector.getMongoDatabase());
    this.userManager = new UserManager(mongoConnector.getMongoDatabase());

    this.guildAudioManager = new MusicManager(this);

    JDABuilder jdaBuilder = JDABuilder.createDefault("..")
            .setActivity(Activity.playing("matar a agallas el perro cobarde"))
            .setChunkingFilter(ChunkingFilter.ALL)
            .enableCache(CacheFlag.VOICE_STATE)
            .setRawEventsEnabled(true)
            .enableIntents(
                    GatewayIntent.GUILD_MEMBERS,
                    GatewayIntent.GUILD_VOICE_STATES,
                    GatewayIntent.DIRECT_MESSAGE_REACTIONS,
                    GatewayIntent.DIRECT_MESSAGE_TYPING,
                    GatewayIntent.DIRECT_MESSAGES,
                    GatewayIntent.GUILD_MESSAGES,
                    GatewayIntent.GUILD_WEBHOOKS,
                    GatewayIntent.GUILD_MESSAGE_REACTIONS
            )
            .setMemberCachePolicy(MemberCachePolicy.ALL);

    this.jda = jdaBuilder.build().awaitReady();

    this.eventWaiter = new EventWaiter();

    jdaBuilder.addEventListeners(
            eventWaiter,
            new ReadyListener(),
            new MemberJoinListener(),
            new ChatListeners(),
            new MusicListeners(this),
            new MayuCoreListener()
    );

    CommandManager commandManager = new CommandManager(jda, "e!");
    commandManager.registerCommands();
    commandManager.init();
  }

  public static void main(String[] args) throws Exception {
    new Bot();
  }

  public Color getColor(String string, Color def) {
    Color out = null;
    if (string == null)
      return def;
    if ("blue".equals(string))
      return Color.BLUE;
    if ("cyan".equals(string))
      return Color.CYAN;
    if ("green".equals(string))
      return Color.GREEN;
    if ("magenta".equals(string))
      return Color.MAGENTA;
    if ("orange".equals(string))
      return Color.ORANGE;
    if ("pink".equals(string))
      return Color.PINK;
    if ("black".equals(string))
      return Color.BLACK;
    if ("white".equals(string))
      return Color.WHITE;
    if ("grey".equals(string))
      return Color.GRAY;
    if ("yellow".equals(string))
      return Color.YELLOW;
    if ("light_grey".equals(string))
      return Color.LIGHT_GRAY;
    if ("red".equals(string))
      return Color.RED;

    out = Color.getColor(string);
    if (out == null)
      out = def;
    return out;
  }

}`

**Comment by HarpyLMAO** [comment] 2021-12-25 23:10
https://www.toptal.com/developers/hastebin/veyaxudomo.csharp

**Comment by lilmayu** [comment] 2021-12-25 23:19
I may suspect where the problem is.
Look at this:
```java
// Loading JDABuilder with stuff
JDABuilder jdaBuilder = JDABuilder.createDefault("..")
            .setActivity(Activity.playing("matar a agallas el perro cobarde"))
            .setChunkingFilter(ChunkingFilter.ALL)
            .enableCache(CacheFlag.VOICE_STATE)
            .setRawEventsEnabled(true)
            .enableIntents(
                    GatewayIntent.GUILD_MEMBERS,
                    GatewayIntent.GUILD_VOICE_STATES,
                    GatewayIntent.DIRECT_MESSAGE_REACTIONS,
                    GatewayIntent.DIRECT_MESSAGE_TYPING,
                    GatewayIntent.DIRECT_MESSAGES,
                    GatewayIntent.GUILD_MESSAGES,
                    GatewayIntent.GUILD_WEBHOOKS,
                    GatewayIntent.GUILD_MESSAGE_REACTIONS
            )
            .setMemberCachePolicy(MemberCachePolicy.ALL);

    this.jda = jdaBuilder.build().awaitReady(); // Builds JDABuilder into JDA object

    // Let's ignore this
    //this.eventWaiter = new EventWaiter();

    jdaBuilder.addEventListeners( // Adds event listeners into **JDABuilder** object AFTER building it - this won't effect previously built JDA object = no event listeners
            eventWaiter,
            new ReadyListener(),
            new MemberJoinListener(),
            new ChatListeners(),
            new MusicListeners(this),
            new MayuCoreListener()
    );
```
With this, this code should maybe work:
```java
JDABuilder jdaBuilder = JDABuilder.createDefault("..")
            .setActivity(Activity.playing("matar a agallas el perro cobarde"))
            .setChunkingFilter(ChunkingFilter.ALL)
            .enableCache(CacheFlag.VOICE_STATE)
            .setRawEventsEnabled(true)
            .enableIntents(
                    GatewayIntent.GUILD_MEMBERS,
                    GatewayIntent.GUILD_VOICE_STATES,
                    GatewayIntent.DIRECT_MESSAGE_REACTIONS,
                    GatewayIntent.DIRECT_MESSAGE_TYPING,
                    GatewayIntent.DIRECT_MESSAGES,
                    GatewayIntent.GUILD_MESSAGES,
                    GatewayIntent.GUILD_WEBHOOKS,
                    GatewayIntent.GUILD_MESSAGE_REACTIONS
            )
            .setMemberCachePolicy(MemberCachePolicy.ALL);
            
    this.eventWaiter = new EventWaiter();

    jdaBuilder.addEventListeners(
            eventWaiter,
            new ReadyListener(),
            new MemberJoinListener(),
            new ChatListeners(),
            new MusicListeners(this),
            new MayuCoreListener()
    );
    
    this.jda = jdaBuilder.build().awaitReady(); // Moved this line of code after adding event listeners - JDABuilder should build into JDA object with those listeners registered
```
I may be wrong thought.

**Comment by HarpyLMAO** [comment] 2021-12-25 23:28
Thank you very much, now works. I owe you one! 👍

**Comment by lilmayu** [comment] 2021-12-25 23:29
Glad to hear that! I am closing this issue.

**Closed by lilmayu** 2021-12-25 23:29 UTC
